sources:
  - name: dvd_rental
    database: dw
    schema: dvd_rental
    tables:
      - name: actor
      - name: actor_info
      - name: address
      - name: category
      - name: city
      - name: country
      - name: customer
      - name: customer_list
      - name: film
      - name: film_actor
      - name: film_category
      - name: film_list
      - name: inventory
      - name: language
      - name: payment
      - name: rental
      - name: staff
      - name: staff_list
      - name: store
